Add matomo tracking script and optout form
hotosm/hugo-book pull request #6
Opened 2019-06-12 14:28 UTC by dakotabenjamin

This PR should enable every docs site to be tracked via Matomo. 

Docs site maintainers/authors will have to get the Matomo site ID from the tech team and add that to their config file.

2019-06-12 15:36 UTC, russbiggs requested changes
@dakotabenjamin - thanks for adding this in! You can remove the changes from the config.yml and the README.md.  Those changes will go in the hotosm/hot-doc-template repo

2019-06-12 15:49 UTC, russbiggs commented
@dakotabenjamin Lets also change ``` {{ .Site.matomoSiteID }} ``` to ``` {{ .Site.params.matomoSiteID }} ``` so that its consistent with other hugo-book variables in the config

2019-06-12 15:53 UTC, dakotabenjamin commented
sorry for all the commits, feel free to squash

2019-06-12 15:55 UTC, russbiggs commented
No problem. One more spot to change here:
https://github.com/hotosm/hugo-book/blob/feature/add-matomo-tracking/layouts/_default/baseof.html#L76

2019-06-15 19:42 UTC, russbiggs approved these changes

2019-06-15 19:42 UTC, merged